### ISSUE TITLE
cannot import name 'keras_modules_injection'

### ISSUE THREAD

**Issue by sunnymoon155** [GuangmingZhu/AttentionConvLSTM#1]
hi author, when I run training_.py, I got error -- cannot import name 'keras_modules_injection'. I have already replace __init__ and convolution_recurrent files to my tensorflow 1.20. how to solve it? thanks!

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/applications/inception_v3.py", line 24,in <module>
    from tensorflow.python.keras.applications import keras_modules_injection
ImportError: cannot import name 'keras_modules_injection'

**Comment by GuangmingZhu** [comment]
@sunnymoon155 Python 2.7 is used.
