### ISSUE TITLE
'module' object has no attribute 'load_iso_video_list'

### ISSUE THREAD

**Issue by yuzuruhanyu** [GuangmingZhu/AttentionConvLSTM#15]
inputs模块中没有load_iso_video_list函数
另外，如果想使用jester集训练，对应的函数是什么呢？
谢谢

**Comment by GuangmingZhu** [comment]
inputs.py中有详细代码

**Comment by yuzuruhanyu** [comment]
我用的0.5版本的inputs，源码里面没找见load_iso_video_list这个函数，请问您用的是哪一个版本的inputs，还是对inputs又进行了修改呢？

**Comment by yuzuruhanyu** [comment]
抱歉，我刚刚理解错了，pip install inputs了。找到你的代码了，谢谢。
