### ISSUE TITLE
ValueError: Only provide the shape OR batch_shape argument to Input, not both at the same time.

### ISSUE THREAD

**Issue by emily19941102** [GuangmingZhu/AttentionConvLSTM#3]
I got the error:
ValueError: Only provide the shape OR batch_shape argument to Input, not both at the same time.
I don't know why? Can you help  me?Thanks!  
@GuangmingZhu

**Comment by GuangmingZhu** [comment]
@emily19941102 Maybe you are using a different (newer) version of TF. If so, you can just modify the code according to the rules of the version you are using.

**Comment by emily19941102** [comment]
@GuangmingZhu Do I need to download Keras? thanks!

**Comment by GuangmingZhu** [comment]
@emily19941102 TF-1.2 contains keras APIs.

**Comment by Charlescai123** [comment]
Hello, I'm just wandering which version do you guys use of the tensorlayer? Cause I've tried to follow what you had installed with the version TF1.2, but failed finally because it warned me that tensorlayer couldn't support TF-version older than 1.6.0. @GuangmingZhu

**Comment by GuangmingZhu** [comment]
@CharlesCai123 Tensorlayer is not used in this pro. Only TF 1.2 is needed.
